spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/auth/**,/superadmin/**,/admin/**,/student/**

        - id: reservation-service
          uri: lb://RESERVATIONMANAGEMENT
          predicates:
            - Path=/reservation/**

        - id: hotel-service
          uri: lb://HOTELMANAGEMENT
          predicates:
            - Path=/hotel/**,/room/**,/location/**,/pricing/**