spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: user-service
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/api/auth/**,/api/users/**

        - id: reservation-service
          uri: lb://RESERVATIONMANAGEMENT
          predicates:
            - Path=/reservation/**

        - id: hotel-service
          uri: lb://HOTELMANAGEMENT
          predicates:
            - Path=/hotel/**,/room/**,/location/**,/pricing/**


eureka:
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10